static/css/base.css
templates/base.html

base.css
template(index, base(nav, foorter)) 생성

[DESIGN]base.css

---

accounts/forms.py
accounts/templates/accounts/login.html
accounts/templates/accounts/signup.html
accounts/views.py
static/css/accounts_login.css
static/css/base.css
static/css/topbutton.css
static/js/topbutton.js
templates/base.html
templates/footer.html
templates/pjt/index.html
templates/topbotton.html

login_template (+css)
base 수정(+html, css)
go_top버튼 생성(+html, css, js)

[FEAT]account_login_template

---

pjt/settings.py
requirements.txt

[UPDATE] settings

---

accounts/templates/accounts/update.html
requirements.txt
static/css/accounts_update.css

[template]
- 닉네임, 이메일, 이미지, 상태메시지 변경 form 추가
[static]
- accounts_update.css 추가

[FEAT] accounts_update template

---

accounts/templates/accounts/signup.html
accounts/templates/accounts/update.html
templates/pjt/index.html

signup, update 사진나오지 않고, 버튼이 안나오는 부분 수정
- forms 고침

[FIX]signup_update

---

accounts/models.py
mountains/models.py
mountains/templates/mountains/course_list.html
mountains/templates/mountains/mountain_detail.html
mountains/templates/mountains/mountain_list.html
mountains/urls.py
mountains/views.py

- 산 리스트 조회
- 산 상세페이지 조회
- 산 코스 리스트 조회(구축중)
- mountains 모델 수정

[ADD] mountains CRUD

---

accounts/views.py

template/profile branch merge 과정에서 누락된 accounts views.py 복원

[FIX] accounts views.py 수정

---

templates/nav.html

[template]
- navbar z-index 값 1000으로 수정

[FIX] nav template

---

mountains/forms.py
mountains/models.py

[FEAT] mountains_review

---

mountains/models.py

mountains 앱의 review 모델 수정(유저 필드 및 이미지 업로드 경로 함수 추가)

[UPDATE] mountains_review

---

mountains/templates/mountains/create_review.html
mountains/urls.py
mountains/views.py

mountains 앱의 review create 기능 구현

[FEAT] review_create

---

mountains/models.py
mountains/urls.py
mountains/views.py

mountains 앱에 review likes 기능 구현

[FEAT] mountains_review likes

---

mountains/forms.py
mountains/models.py
mountains/templates/mountains/mountain_detail.html
mountains/templates/mountains/mountain_list.html
mountains/urls.py
mountains/views.py

[ADD] course_bookamark

---

mountains/models.py
mountains/templates/mountains/course_list.html
mountains/templates/mountains/mountain_detail.html
mountains/urls.py
mountains/views.py

- 코스 리스트 기능 구축(전체, 북마크 순 필터 기능도 추가함)
- 산 좋아요 기능 구축(비동기 적용함)
- 산 조회수 기능 오류 디버깅

[ADD] course_list, mountain_like

---

posts/templates/posts/detail.html
posts/views.py

img : 변수명 오류 -> 수정
이전/이후 게시글 제대로 추가
수정 부분 확인 -> 성주님이 원하시는 부분에 가져다 놓기를 요망

[FIX]posts_detail

---

mountains/templates/mountains/review_detail.html
mountains/urls.py
mountains/views.py

mountains 앱의 review update 기능 구현
- 리뷰 디테일 페이지에서 수정 버튼 클릭시 모달창이 뜨며 해당 창에서 수정 가능.

[FEAT] mountains_review update

---

accounts/templates/accounts/profile.html
accounts/views.py
mountains/views.py
static/css/profile.css

[template]
북마크한 코스,
좋아요한 산 목록 추가
그 외 기타 코드정리

[UPDATE] accounts_profile

---

static/css/mountains_detail.css
static/css/posts_index.css
static/js/posts_index.js

좋아요 버튼 누를시
좋아요 숫자가 undefined로 출력되는 버그 수정

[FIX] posts_index

---

mountains/templates/mountains/mountain_detail.html
static/css/mountains_detail.css

[template]
-mountain map modal open시 중심좌표 어긋나는 부분 수정

[FIX] mountains_detail

---

posts/templates/posts/index.html
posts/templates/posts/search.html
static/css/posts_index.css
static/js/posts_index.js

[template]
index 
- index like, view 랭킹 8개까지만 보이게 수정
- search form 디자인 및 url 경로 index -> search로 수정
search
- search form 디자인 및 url 경로 index -> search로 수정 
- 검색시 입력한 query 부분 main color 적용
js
- search template 에서도 좋아요 비동기 가능하게 코드 수정

[UPDATE] posts_search, index

---

accounts/templates/accounts/profile.html
accounts/templates/accounts/update.html

account 앱 프로필 수정시 닉네임이 없으면 모달창이 뜨도록 수정.

[UPDATE]accounts_update

---

accounts/models.py
mountains/templates/mountains/course_list.html
mountains/views.py
static/js/mountain_course.js

- 코스 상세 리스트 최적화(linestring으로 point보다 속도를 높임)

[OPTIMIZE] course

---

mountains/templates/mountains/mountain_detail.html
mountains/views.py

[OPTIMIZE] mountains_detail

---

mountains/templates/mountains/course_list.html
mountains/views.py

지워진 부분 수정
지도를 못 불러와서 내가 했던대로 geojson_data 변경
for course in courses:
geojson_data = serializer.serialize([course], geometry_field='geom')
data[course.pk] = geojson_data
↓
코스를 필드별로 불러옴
for course in page_obj:
geojson_data = serializer.serialize(CourseDetail.objects.filter(crs_name_detail=course), fields=('geom', 'is_waypoint', 'waypoint_name', 'crs_name_detail'))
data[course.pk] = geojson_data

[FIX]mountains_views

---

mountains/models.py

- 산 모델 수정(이미지 필드 삭제, info 필드 추가)

[UPDATE] Mountain Model

---

mountains/views/views.py
static/css/base.css
templates/nav.html

[FEAT] mountains_search

---

posts/templates/posts/proofshot.html

[UPDATE] proofshot template

---

posts/templates/posts/proofshot.html
posts/views.py
templates/nav.html
templates/pjt/index.html

- nav, index 링크 연결
- proofshot 일부 수정

[ORGANIZAITION] etc

---

mountains/templates/mountains/mountain_detail.html
mountains/views/detail_views.py

- detail 부분, 베스트 댓글, 산 정보 템플릿 입력 및 js 기능 추가

[FIX] mountains_detail_template

---

accounts/templates/accounts/delete.html

accounts 앱의 delete(회원탈퇴) 템플릿 수정
- 회원탈퇴 확인창에서 취소시에도 탈퇴가 되던 오류 수정

[FIX] accounts_delete

---

posts/templates/posts/index.html
posts/templates/posts/search.html
posts/views.py
static/css/posts_index.css
static/js/posts_index.js

[template]
- post 디자인 변경
[js]
- 좋아요 비동기 수정

[UPDATE] template/posts_index, search

---

accounts/templates/accounts/my_memories.html
accounts/views.py

[UPDATE]my_memories

---

accounts/templates/accounts/profile.html
accounts/views.py

accounts 앱의 profile 뷰 수정(로딩 속도 개선)
- 카카오맵 API 코드부분은 주석처리함

[FIX] accounts_profile

---

mountains/templates/mountains/course_list.html
mountains/urls.py
mountains/views/views.py
pjt/settings.py
requirements.txt

- 각 코스 GPX 다운로드 및 이메일 전송 기능 구현

[ADD] GPX download

---

accounts/forms.py

[FIX] profile_update_msg_layout

---

templates/footer.html

[ADD] footer

---

accounts/views.py

카카오 로그인시 이메일 또는 이미지를 가져오지 않을 때 발생하는 오류 해결

[FIX] accounts_kakao_login

---

mountains/urls.py
mountains/views/views.py

[FIX] filtering

---

mountains/views/detail_views.py
mountains/views/views.py
templates/pjt/index.html

- 메인 인덱스 일부 폰트 수정
- app mountains 권한 설정

[CHORE] etc

---

accounts/views.py

accounts 앱의 로그인 기능 수정
- 로그인하면 이전 페이지로 이동(로그아웃, 회원탈퇴 페이지 제외)

[FIX] accounts_login

---

mountains/templates/mountains/course_list.html
static/js/mountain_course.js

[UPDATE] waypoint checkbox

---

accounts/templates/accounts/notification.html
posts/forms.py
posts/templates/posts/detail.html
posts/templates/posts/update.html
posts/views.py
templates/nav.html

detail 오타 수정
update 페이지 오류(폼 변경 후 필드 추가 누락)
notification 수정

[FIX] posts

---

mountains/templates/mountains/review_update.html

mountains 앱의 리뷰 수정시 발생하는 오류 수정

[FIX] mountains_review_update

---

mountains/templates/mountains/course_detail.html

[ADD] gpx_memory

---

accounts/views.py

accounts 앱의 소셜 로그인 기능 코드 수정
- 모델 이미지 필드 변경으로 인한 코드 수정

[FIX] accounts_social_login

---

mountains/templates/mountains/weather_forecast.html
mountains/views/views.py

[UPDATE] weather_forecast

---

.gitignore
mountains/templates/mountains/course_detail.html
mountains/templates/mountains/course_list.html
mountains/templates/mountains/mountain_detail.html
mountains/views/detail_views.py
static/js/accounts_mymemories_map.js
static/js/mountain_course.js

- 환경변수 추가
- .gitignore에 api.js 추가

[UPDATE] env

---

accounts/templates/accounts/my_memories.html

[FIX] accounts_my_memories

---

mountains/templates/mountains/mountain_detail.html
mountains/templates/mountains/weather_forcast.html
mountains/templates/mountains/weather_forecast.html
mountains/views/views.py
static/css/mountains_detail.css
static/css/mountains_weather.css
static/js/mountains_weather.js

[template]
- weather_forecast 템플릿 디자인

[UPDATE] mountain_weather

---

accounts/views.py

accounts앱의 naver login 코드 수정
- 네이버 프로필 이미지 불러오기

[FIX] accounts_naver_login

---

accounts/views.py
templates/pjt/mainindex.html

logout,delete : mainindex 경로수정

[FIX]logout

---

mountains/models.py
mountains/views/detail_views.py
pjt/settings.py
pjt/urls.py
requirements.txt

[CHORE] organization

---

mountains/templates/mountains/mountain_detail.html
mountains/views/detail_views.py
posts/templates/posts/proofshot.html
posts/templates/posts/search.html
static/css/mountains_detail.css
static/css/mountains_weather.css

[template]
mountains_detail
- best 리뷰가 없는데도 불구하고 info best태그 쪽에 "" 가 출력 되는 현상 수정
- 태그 없는데 info img 쪽에 태그bar가 출력되는 현상 수정
- 코스 더보기 버튼 위치조정 및 디자인 변경
- 지도 보기 클릭시 modal 화면에 지도가 제대로 출력되지 않는 현상 수정
- 관련뉴스에 &quot; 로 출력되고 있는 현상 수정
- 작성된 마이코스가 없는경우 (작성된 글이 없습니다) 가운데 출력하게 수정
weather_forecast
- navbar와 content 사이 margin 간격 조절
posts_search
- userimg 에 level 에 따른 테두리가 생기지 않는 현상 수정
proofshot
- container 양쪽 간격 조절

[FIX] templates

---

pjt/settings.py

- 배포위한static_root 설정 및 debug=false

[DEPLOY] settings_py

---

mountains/views/detail_views.py

[TEST] weather api

---

mountains/views/detail_views.py
pjt/settings.py

[DEPLOY] etc
